// next/head permet d'injecter du code dans le head de notre HTML
import Head from "next/head";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
// nextAuth va nous permettre d'avoir les informations de la session de l'utilisateur côté serveur
import { getSession } from "next-auth/react";
import { useSession, signIn } from "next-auth/react";

export default function Home() {
  // Si l'utilisateur est connecté il va sur la page index, sinon, il passe par la page Login (component)
  // useSession est un Booléen qui permet de vérifier si un utilisateur est connecté ou non, on le place ensuite dans une variable
  const { data: session } = useSession();
  if (session) {
    return (
      <div>
        <Head>
          <title>Groupomania</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Header */}
        <Header />

        <main className="flex">
          {/* Sidebar */}
          <Sidebar />
          {/* Feed */}
          {/* Widgets */}
        </main>
      </div>
    );
  }
  return <Login />;
}

// Incorporation du SSR (Server Side Rendering)
export async function getServerSideProps(context) {
  // Get the user (the context is the user request)
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
